package br.com.fiap.delegacia.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class ConnectionFactory {
    private static final ConnectionFactory INSTANCE = new ConnectionFactory();
    private final String url = System.getenv().getOrDefault("DB_URL", "jdbc:h2:file:./data/delegacia");

    private ConnectionFactory() {}

    public static ConnectionFactory getInstance() {
        return INSTANCE;
    }

    public Connection getConnection() throws SQLException {
        boolean h2 = url.startsWith("jdbc:h2:");
        String user = System.getenv().getOrDefault("DB_USER", h2 ? "sa" : "");
        String password = System.getenv().getOrDefault("DB_PASSWORD", "");
        Connection connection = DriverManager.getConnection(url, user, password);
        if (h2) {
            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("""
                        CREATE TABLE IF NOT EXISTS delegacia (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(255) NOT NULL,
                            endereco VARCHAR(500) NOT NULL
                        )
                        """);
                statement.executeUpdate("""
                        CREATE TABLE IF NOT EXISTS policial (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(255) NOT NULL,
                            cpf VARCHAR(20) NOT NULL UNIQUE,
                            matricula VARCHAR(50) NOT NULL UNIQUE,
                            cargo VARCHAR(100) NOT NULL,
                            delegacia_id BIGINT NOT NULL REFERENCES delegacia(id)
                        )
                        """);
                statement.executeUpdate("""
                        INSERT INTO delegacia (nome, endereco)
                        SELECT 'Delegacia de demonstracao', 'Endereco de demonstracao'
                        WHERE NOT EXISTS (SELECT 1 FROM delegacia)
                        """);
            } catch (SQLException e) {
                connection.close();
                throw e;
            }
        }
        return connection;
    }
}
