CREATE TABLE delegacia (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    endereco VARCHAR2(500) NOT NULL
);

CREATE TABLE policial (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    cpf VARCHAR2(20) NOT NULL UNIQUE,
    matricula VARCHAR2(50) NOT NULL UNIQUE,
    cargo VARCHAR2(100) NOT NULL,
    delegacia_id NUMBER NOT NULL REFERENCES delegacia(id)
);

INSERT INTO delegacia (nome, endereco)
VALUES ('Delegacia de demonstracao', 'Endereco de demonstracao');
